Mizar用のLS拡張機能を作成
mimosa-project/emlsp pull request #1
Opened 2022-03-30 23:49 UTC by mhrwh

* mizar extension を参考に，mizar language serverを作成しました．
* それを使用したVSCode用のLanguage Server 拡張機能を作成しました．

2022-03-31 04:55 UTC, aabaa requested changes

2022-03-31 04:55 UTC, aabaa commented on server/src/hover.ts
> +        "end": { "line": position.line, "character": 100 }
100をこの行の最後に直す

2022-03-31 04:55 UTC, aabaa commented on server/src/mizarFunctions.ts
> +                    //channel.clear();
以下が動作するか試してみる
https://stackoverflow.com/questions/9006988/node-js-on-windows-how-to-clear-console

2022-04-04 06:15 UTC, mhrwh commented on server/src/mizarFunctions.ts
> +                    //channel.clear();
全て試しましたがうまく動作しませんでした

2022-04-05 04:56 UTC, merged